### ISSUE TITLE
Dominator GTX speed adjustment.

### ISSUE THREAD

**Issue by XBTech** [InZidiuZ/op-framework-bug-tracker#100]
On the left you will see the regular dominator stock version. On the right you have the Dominator GTX.  The one on the left costs 5.5k to finance and the one on the right is 3 times as much for 15k to finance. Normally you would think that the one on the right would be better in terms of performance. Although, the one on the right only reached a top speed of 104mph in a downhill motion. In contrary the regular dominator reached 150mph no problem without even being at top speed. Further testing have shown that even the flat bed can reach a higher top speed then the GTX.
![IMG_20190625_202021](https://user-images.githubusercontent.com/43392378/60278925-361bfe80-98ce-11e9-856c-5de88819a1f9.jpg)

(Please note that I already have mentioned this to Karpenko I just wanted you to be aware of it.)

**Comment by InZidiuZ** [comment]
Hey,

This is due to the custom handlings we use not being up to date with the latest GTA vehicles. I believe Karpenko will be going through all those vehicles without custom handlings & create matching ones for those as well. Will close this though, as this is more of an assets-related thing, & as you said, Karpenko is aware already. :)

**InZidiuZ**
*OP-FW Develoepr*
