### ISSUE TITLE
Potential Commission idea for Dealership

### ISSUE THREAD

**Issue by SirPiff** [InZidiuZ/op-framework-bug-tracker#101]
So, I recently asked about if commission was a planned feature that was going to be implemented, and there were clearly a couple of issues that arose with such an idea, which I may have a suggestion that could potentially work, but won’t be overpowered if someone were to buy a super-car.

Since Ben’s main issue with commission is that even 10% might be a lot in some cases, my proposition is to create a set amount that the dealer could make off a sale depending on the vehicle class.

So for an example:

- Supers - $800
- Sports - $500
- Muscle - $400
- Anything else - $300

Of course, this would require many tweaks and balancing, but I believe that it would definitely be a way for car dealers to make a commission from sales without it being OP.

The command to sell to a player could look like this.
/sellcar [server id] [veh slot] [finance or full]

This may, however, take some time to code. Share your thoughts!

Discord: Piff#7611

**Comment by InZidiuZ** [comment]
Hey,

Instead of creating a system like you suggested, I've created a system which lets the dealers set a commission % between 0-15%. The buyer will have to pay the upfront amount, together with the commission fee. So to finance a $40k vehicle, you normally would pay $10k up front, but with a 10% commission, you would be paying $11k. This would not apply for the finances. Paying the entire sum for a $40k vehicle would then cost $44k.

The dealer responsible for setting the commission will currently get a 20% of the commission sum, so for that $40k vehicle with a 10% commission, the salesperson would receive $800. Not sure how balanced this will be, so feel free to give feedback on this system in a couple of days/weeks.

To set a commission, all you must do as a dealer is walk up to the vehicle and hit E.

You will only receive your portion of the commission if you're online on the server when the purchase goes through, as commissioning a vehicle should only be a thing when you help a customer to purchase a vehicle. Attempting to abuse this system by setting a % on the displayed vehicles for quick cash won't be tolerated, not that it would work very well.

lol, hopefully you didn't lose too many brain cells reading through that explanation.

**InZidiuZ**
*OP-FW Developer*

**Comment by SirPiff** [comment]
Only one question, when you set the commission, does the server then recognize you as the seller?
Cause if multiple dealers are online at the same time, it'd be weird if we all got a commission.

I like the idea though! Looking forward to checking it out.

I'll let you know if it seems to OP and will report anyone abusing this.
Thanks for all your hard work dad <3

**Comment by InZidiuZ** [comment]
> The dealer responsible for setting the commission

Yes, the server does recognize you/your character

**Comment by SirPiff** [comment]
Minor Concern:

Let's say we bring out a new car, will the car be already set at the max price but without being attached to a salesman?

I believe they should so that if people want cheaper prices they have to go through us, and if they aren't, it might be a little weird discussing the car and all of a sudden the price going up because the salesman added the commission if you understand where I'm coming from.

Let's say someone is looking at the Feltzer, which is currently a 50K Car.
They're ready to buy but you'd like even a little bit of commission. It'd be weird to see the cars be **more** expensive than usual **with** a salesman rather than without.

So they end up leaving and saying they're not going to buy with commission, and the dealer has to put the commission down otherwise the cars on display will already have it set for that salesman, then they can just run in, flex a muscle, and have a new car for cheaper than intended.

If you are to set the price to the max without it being "selected" to a certain salesman so they're maxed, I'd suggest a "reset commission" button that'll unbind the salesman from the car.

Just a bit of a concern, that's all, maybe you've already tackled this issue.
