### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by neonbananer** [InZidiuZ/op-framework-bug-tracker#120]
**Name:**
xdman #8321

**Summary:**
ubermacht sentinel classic and annis elegy retro custom cant break 120 mph with an upgraded engine.

**Reason:**
both of these cars were pretty expensive and even with upgraded engines arent able to go faster than a sedan off the street and i really dont think it should be this way.

**Comment by InZidiuZ** [comment]
Hey,

Same as #100.

"This is due to the custom handlings we use not being up to date with the latest GTA vehicles. I believe Karpenko will be going through all those vehicles without custom handlings & create matching ones for those as well. Will close this though, as this is more of an assets-related thing, & as you said, Karpenko is aware already."

**InZidiuZ**
*OP-FW Developer*
