### ISSUE TITLE
ID Job doesn't change when changing jobs

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#21]
Put very simply, when you change jobs the job on your ID doesn't change with it. Video included: https://streamable.com/t0rv4

**Comment by InZidiuZ** [comment]
Hmm, yea. Don't think I would want it to automatically update though, because:
- It's not realistic.
- Performance.
- Might be difficult properly changing the metadata properly, without creating a million complications.
- If we make this update, should we make ID cards static to yourself? So if you take someone else's ID card, would that ID card suddenly be bound to them?

Personally feel like buying a new one when _truly_ changing job could work just fine, or just let anyone reading your card know that it's a bit outdated, and that your job isn't what it says anymore.

Jobs aren't really needed on an ID card anyways.

**Comment by sammikins** [comment]
Ohhhh, so you have to buy a new card. Gotcha
