### ISSUE TITLE
Two Keys for the Same Car

### ISSUE THREAD

**Issue by sammikins** [InZidiuZ/op-framework-bug-tracker#30]
Here are the steps to creating multiple keys for the same car.

* First you must own the vehicle
* Pull the car out of a garage to get a key
* Hand the key to someone
* Store the car in a garage
* Pull the car back out of the garage

Now you should have two keys for the same car. It's somewhat convenient to be able to have two keys for the same car but this is an unintended way of achieving it. Instead, perhaps a service at the garage to buy a second key for the car?

The system as it is could have some very unintended consequences. Someone may not know that another person is holding onto a duplicate of this key and could potentially raid the inventory of the car or just steal the car.

Again, this can be okay if the duplication was intentional but this is currently a glitch method of duplicating the key. I think there should be a feature added to do this.

**Comment by InZidiuZ** [comment]
Initially I had the garage delete all keys when depositing a car, even if it was in another inventory. But due to this causing some unwanted complications, I left it be, and now keys will only be delete if they're in your own inventory. So yes, it was intentional. If you wish to get rid of the key, keep it in your inventory, otherwise, give it to someone else or drop it on the ground.
