### ISSUE TITLE
A few complaints about the new framework.

### ISSUE THREAD

**Issue by Night0wI** [InZidiuZ/op-framework-bug-tracker#55]
Repairing your car shouldn't be as hard as it is right now:
Only 2 repair shops on the map.
Repair shops need "materials" that most new players won't be able to get.
The repair shop in the middle of town will make your car get stuck if it's the size of a truck.
Only 2 tool shops on the map.
Basic repair kit is useless. Even after using it on my semi-truck, it's still smoking and engine keeps turning off every now and then, and I can't afford to buy an advanced kit. Haven't seen any mechanics around either.
Getting a car to drive around with is painful. Dealerships now sell cars that are on display, which are usually very expensive and impossible to purchase for new players. And if a new player decides they'll steal a car off the streets, hotwiring has like a 10% chance of success, by which cops will probably have already seen you and arrest you.
So, it is currently frustrating to start out fresh without having a way of buying a car/getting a car. And even more frustrating to repair one after you got it. I have played for around 4 hours and my entire experience was walking to LifeInvader and going to my job place then trying to fix my semi-truck.

**Comment by InZidiuZ** [comment]
Hey,

Sounds like you may've had a bad start.

* Repairing your car isn't very difficult. Either get a mechanic to do it for you, or have the materials on you and repair it yourself. It can be done in a couple of minutes.
* Materials can either be purchased, or gathered through various *jobs* (diving/chop shop). If you don't want to do so, you can purchase from other players, or from the server itself. The server being overpriced to encourage RP.
* The repair shop at Grove Street is limited to small cars, use the one at the Terminal for larger vehicles.
* There are only 2 repair shops on the map to create more interactions there, instead of having 20, and no interactions.
* Basic repair kits are not useless, they're supposed to get your car working if it's broken down, but nothing more.
* Mechanics are around, you just have to look better. Using your phone/twitter is also helpful. If you still can't find any, become one.
* They're mostly selling med-low end cars, and you can also get in contact with a salesperson if you wish to purchase a specific or cheap car, all creating RP.
* You can purchase a gun and force NPCs to hop out & give you their keys.
* The chance of successfully hotwiring a vehicle is also 20% without a lockpick, 40% with a basic one, and 100% with an advanced one. You could also call a taxi, or even become one if there's none in town.

This is an entirely new server built from scratch, so it's not like the other thousands of FiveM servers. You'll have to spend time learning the game mechanics if you wish to play, and that doesn't happen in a couple of hours.

Will close this issue as it didn't pick up any conversation, but if you wish to post it somewhere else, I'd recommend the forum.

**InZidiuZ**
*OP-FW Developer*
