### ISSUE TITLE
Some Bugs I have found

### ISSUE THREAD

**Issue by Cricketx818** [InZidiuZ/op-framework-bug-tracker#79]
1)I have found out that, If you have 3-5 keys in your inventory, and you drop them all at the same time, Then you place something in those certain spots, They all stack on top of each other and turn into keys, (example: I dropped 5 keys, I bought 12 bandages my bandages turned into 12 keys)

2) cars that get stolen/Crashed in the middle of the street Never disappear the city

3) Phones sometimes work and sometimes dont

**Comment by InZidiuZ** [comment]
Hey,

1. This is a known issue, and is to be investigated.
2. "Abandoned vehicles" would be a better way to put this, and it's intentional to prevent vehicles from being deleted whenever not looking at them, or being too far away. This will probably be tweaked to only allow you to have one such "marked" vehicle at a time, instead of having 5 in the city, 2 in north, and a bunch laying around on the highway.
3. This is a known issue, and will be sorted soon.

**InZidiuZ**
*OP-FW Developer*

**Comment by InZidiuZ** [comment]
Will close this as 2 & 3 will both have been sorted after the next update, and 1 is in my to-do list.
